version: '2'
services:
   repo:
      image: registry:2 
      container_name: repo
      restart: always
      ports:
        - 5000:5000
      environment:
        - REGISTRY_STORAGE_DELETE_ENABLED=true
      volumes:
        - ./registry:/var/lib/registry