version: "3.7"

services:
  zentao:
    image: easysoft/zentao:12.3.3
    container_name: zentao
    ports:
      - 9001:80
      - 3306:3306
    volumes:
      - ./pms:/www/zentaopms
      - ./mysqldata:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: 123456
    networks:
      zentaonet:
        ipv4_address: 172.172.172.2

networks:
  zentaonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.172.172.0/24