version: '3'

services:
  consul-server-1:
    image: consul:latest
    ports:
        - "8401:8400"
        - "8501:8500"
        - "8601:8600"
        - "8601:8600/udp"
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    image: consul:latest
    ports:
        - "8402:8400"
        - "8502:8500"
        - "8602:8600"
        - "8602:8600/udp"
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    image: consul:latest
    ports:
      - "8403:8400"
      - "8503:8500"
      - "8603:8600"
      - "8603:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"