


version: '3'

services:
   db:
     image: mysql:5.6
     container_name: gopub-mysql
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: walle
       MYSQL_USER: gopub
       MYSQL_PASSWORD: gopub
     ports:
       - 3306:3306

   gopub:
     depends_on:
       - db
     image: lc13579443/gopub
     container_name: gopub
     ports:
       - 8192:8192
     restart: always
     environment:
       MYSQL_HOST: gopub-mysql
       MYSQL_PORT: 3306
       MYSQL_USER: root
       MYSQL_PASS: 123456
       MYSQL_DB: walle
