version: "3.7"
services:
  yapi:
    image: yapipro/yapi:1.9.5
    container_name: yapi
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./conf/config.json:/yapi/config.json
    networks:
      - yapinet
    command: "server/app.js"

  mongodb:
    image: mongo:4.2.8
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-data:/data/db
    networks:
      - yapinet
    environment:
      MONGO_INITDB_DATABASE: yapi
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

networks:
  yapinet:
    driver: bridge