version: '2'
services:
  ftpd_server:
    image: stilliard/pure-ftpd:latest
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data:/home/ftpuser/"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      FTP_PASSIVE_PORTS: 30000:30009
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: wuji
      FTP_USER_PASS: wuji
      MaxClientsNumber: 100
      FTP_USER_HOME: /home/ftpuser
    restart: always

