
version: '2'
services:
  db:
    image: mysql:5.6
    restart: always
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
    ports:
      - '3306:3306'
